# Generated by Django 3.1.1 on 2020-09-18 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dhcp4', models.BooleanField(default=True)),
                ('dhcp6', models.BooleanField(default=True)),
                ('mac', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='wanlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wanlan', models.CharField(max_length=10)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlpanel.iface')),
            ],
        ),
    ]
