# Generated by Django 3.1.1 on 2020-09-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(choices=[('Filter', 'Filter'), ('NAT', 'Nat'), ('Mangle', 'Mangle'), ('Raw', 'Raw')], default='Filter', max_length=6)),
            ],
        ),
    ]
