# Generated by Django 3.1.1 on 2020-09-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0002_iptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='protocol',
            field=models.CharField(choices=[('udp', 'Udp'), ('tcp', 'Tcp'), ('icmp', 'Icmp')], default='tcp', max_length=10),
        ),
    ]
