# Generated by Django 3.1.1 on 2020-09-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0003_iptable_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='action',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('DROP', 'Drop'), ('REJECT', 'Reject'), ('FORWARD', 'Forward'), ('MASQUERADE', 'Masquerade')], default='DROP', max_length=10),
        ),
        migrations.AddField(
            model_name='iptable',
            name='destination',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='iptable',
            name='in_iface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iface_ingress', to='controlpanel.iface'),
        ),
        migrations.AddField(
            model_name='iptable',
            name='out_iface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iface_egress', to='controlpanel.iface'),
        ),
        migrations.AddField(
            model_name='iptable',
            name='port',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='iptable',
            name='source',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
