# Generated by Django 3.1.1 on 2020-09-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0004_auto_20200918_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
