# Generated by Django 3.1.1 on 2020-09-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0005_iptable_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='removable',
            field=models.BooleanField(default=True),
        ),
    ]
