# Generated by Django 3.1.1 on 2020-09-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0006_iptable_removable'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='chain',
            field=models.CharField(choices=[('INPUT', 'Input'), ('OUTPUT', 'Output'), ('FORWARD', 'Forward'), ('ROUTING', 'Routing'), ('PREROUTING', 'Prerouting'), ('POSTROUTING', 'Postrouting')], default='INPUT', max_length=20),
        ),
        migrations.AddField(
            model_name='iptable',
            name='sport',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
