# Generated by Django 3.1.1 on 2020-09-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0007_auto_20200918_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='options',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
