# Generated by Django 3.1.1 on 2020-09-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0009_auto_20200918_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTablePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(choices=[('Filter', 'Filter'), ('NAT', 'Nat'), ('Mangle', 'Mangle'), ('Raw', 'Raw')], default='Filter', max_length=6)),
                ('chain', models.CharField(choices=[('INPUT', 'Input'), ('OUTPUT', 'Output'), ('FORWARD', 'Forward'), ('ROUTING', 'Routing'), ('PREROUTING', 'Prerouting'), ('POSTROUTING', 'Postrouting')], default='INPUT', max_length=20)),
                ('policy', models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('DROP', 'Drop')], default='ACCEPT', max_length=6)),
            ],
        ),
    ]
