# Generated by Django 3.1.1 on 2020-09-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0011_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='apply_iptables',
            field=models.BooleanField(default=True),
        ),
    ]
