# Generated by Django 3.1.1 on 2020-09-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0012_auto_20200922_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptable',
            name='protocol',
            field=models.CharField(choices=[('all', 'All'), ('udp', 'Udp'), ('tcp', 'Tcp'), ('icmp', 'Icmp')], default='tcp', max_length=10),
        ),
        migrations.AlterField(
            model_name='iptable',
            name='table',
            field=models.CharField(choices=[('filter', 'Filter'), ('nat', 'Nat'), ('mangle', 'Mangle'), ('raw', 'Raw')], default='filter', max_length=6),
        ),
        migrations.AlterField(
            model_name='iptablepolicy',
            name='table',
            field=models.CharField(choices=[('filter', 'Filter'), ('nat', 'Nat'), ('mangle', 'Mangle'), ('raw', 'Raw')], default='filter', max_length=6),
        ),
    ]
