# Generated by Django 3.1.1 on 2020-09-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0013_auto_20200922_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='match',
            field=models.CharField(blank=True, choices=[('state', 'State')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='iptable',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
