# Generated by Django 3.1.1 on 2020-09-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0015_auto_20200922_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPSubnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=15)),
                ('start', models.CharField(max_length=15)),
                ('end', models.CharField(max_length=15)),
                ('gateway', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_needed', models.BooleanField(default=True)),
                ('bogus_priv', models.BooleanField(default=True)),
                ('no_resolv', models.BooleanField(default=True)),
                ('expand_hosts', models.BooleanField(default=True)),
                ('ns_1', models.CharField(max_length=23)),
                ('ns_2', models.CharField(max_length=23)),
                ('ns_3', models.CharField(max_length=23)),
            ],
        ),
    ]
