# Generated by Django 3.1.1 on 2020-09-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0016_dhcpsubnet_dns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dns',
            name='ns_1',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='dns',
            name='ns_2',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='dns',
            name='ns_3',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
