# Generated by Django 3.1.1 on 2020-09-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0017_auto_20200924_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpsubnet',
            name='netmask',
            field=models.CharField(default='255.255.255.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='dhcpsubnet',
            name='end',
            field=models.CharField(default='192.168.100.50', max_length=15),
        ),
        migrations.AlterField(
            model_name='dhcpsubnet',
            name='network',
            field=models.CharField(default='192.168.100.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='dhcpsubnet',
            name='start',
            field=models.CharField(default='192.168.100.2', max_length=15),
        ),
    ]
