# Generated by Django 3.1.1 on 2020-09-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0018_auto_20200924_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpsubnet',
            name='lease_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dhcpsubnet',
            name='min_hour',
            field=models.CharField(choices=[('minute', 'Min'), ('hour', 'Hour')], default='hour', max_length=6),
        ),
    ]
