# Generated by Django 3.1.1 on 2020-09-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0022_system_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='unattended_upgrades',
            field=models.BooleanField(default=False),
        ),
    ]
