# Generated by Django 3.1.1 on 2020-09-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0024_blocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
