# Generated by Django 3.1.1 on 2020-09-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0025_blocklist_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='apply_dnsmasq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='system',
            name='apply_ipaddrs',
            field=models.BooleanField(default=False),
        ),
    ]
