# Generated by Django 3.1.1 on 2020-09-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0026_auto_20200926_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
